name: RustDemo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: codebuild-GitHubActionsDemo-${{ github.run_id }}-${{ github.run_attempt }}-linux-lambda-nodejs20-1GB
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: apt-get install xz-utils
      - name: Install Zig toolchain
        uses: goto-bus-stop/setup-zig@v2
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: cargo-lambda/cargo-lambda
          tag: v0.14.0 
          platform: linux 
          arch: x86_64 
          # Add your build steps below
      - name: Build Rust API
        uses: actions/checkout@v4
      - run: cargo lambda build --release
      - run: cargo lambda deploy 
